pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Building...'
                    sh 'docker run --rm -v "123":/usr/src/app -w /usr/src/app node:14 npm install'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo 'Running Tests...'
                    sh 'docker run --rm -v "123":/usr/src/app -w /usr/src/app node:14 npm test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    echo 'Building Docker Image...'
                    sh 'docker build -t nashaat111/netflix-app:latest .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    echo 'Pushing Docker Image to Registry...'
                    sh 'docker login -u nashaat111 -p Nashaat123#'
                    sh 'docker push nashaat111/netflix-app:latest'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo 'Deploying to Kubernetes...'
                    sh 'kubectl apply -f k8s/deployment.yaml'
                    sh 'kubectl apply -f k8s/service.yaml'
                }
            }
        }
    }
}

