pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the version control system
                git 'https://github.com/Nashat-Ahmed/demo1.git'
            }
        }

        stage('Build') {
            steps {
                // Build the Maven project
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                // Run the unit tests
                sh 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build Docker image
                script {
                    def dockerImage = docker.build("nashaat111/java-maven-app:${env.BUILD_ID}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                // Push Docker image to Docker Hub (ensure you're logged in)
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        def dockerImage = docker.build("nashaat111/java-maven-app:${env.BUILD_ID}")
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                // Deploy the application (e.g., Kubernetes, Docker Swarm, etc.)
                echo 'Deploying to the environment...'
                // Add your deployment steps here
            }
        }
    }
}

